import express from 'express';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';

const router = express.Router();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const EVIDENCE_DIR = path.join(__dirname, '../evidence');
const SECRET_KEY = process.env.EVIDENCE_SECRET || 'erasmus_super_secret_key_2026';

// Ensure evidence directory exists
if (!fs.existsSync(EVIDENCE_DIR)) {
    fs.mkdirSync(EVIDENCE_DIR, { recursive: true });
}

// POST /api/evidence
router.post('/', (req, res) => {
    try {
        const { userId, simulationId, parameters, result } = req.body;

        if (!userId || !simulationId || !parameters) {
            return res.status(400).json({ error: 'Missing required fields' });
        }

        const timestamp = new Date().toISOString();
        const sessionId = crypto.randomUUID();

        // Construct the immutable log entry
        const logEntry = {
            header: {
                standard: "Erasmus+ VET Evidence v1.0",
                timestamp: timestamp,
                session_id: sessionId,
                integrity_hash_algo: "HMAC-SHA256"
            },
            student: {
                user_id: userId,
                // In production, we would fetch student name from DB here to ensure authenticity
            },
            simulation: {
                id: simulationId,
                parameters: parameters,
                result: result
            }
        };

        // Create Cryptographic Signature
        // Only the server knows the SECRET_KEY, so this proves the log was generated by the platform.
        const payloadString = JSON.stringify(logEntry);
        const signature = crypto
            .createHmac('sha256', SECRET_KEY)
            .update(payloadString)
            .digest('hex');

        const finalRecord = {
            ...logEntry,
            signature: signature
        };

        // Save to Disk (Immutable WORM simulation)
        const filename = `evidence_${sessionId}.json`;
        const filePath = path.join(EVIDENCE_DIR, filename);
        
        fs.writeFileSync(filePath, JSON.stringify(finalRecord, null, 2));

        console.log(`[Evidence] Generated proof for session ${sessionId}`);

        res.json({
            success: true,
            sessionId: sessionId,
            signature: signature,
            downloadUrl: `/api/evidence/${filename}` // In a real app, this would be a protected route
        });

    } catch (err) {
        console.error('[Evidence] Generation failed:', err);
        res.status(500).json({ error: 'Failed to generate evidence' });
    }
});

export default router;
